# Widoco configuration properties
# See https://github.com/dgarijo/Widoco for available options

abstract=An OWL ontology describing wines, grape varieties, and wineries.
ontologyTitle=Wine Ontology
ontologyPrefix=wine
ontologyNamespaceURI=http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#
